version: '3'

services:

  composer:
    image: composer
    volumes:
      - .:/app
    working_dir: /app

  php:
    build: docker/php${PHP_VERSION}-xdebug
    volumes:
      - .:/app
    working_dir: /app
